### ISSUE TITLE
Dados criticos

### ISSUE THREAD

**Issue by guimar86** [MarioFGomes/NotificationAPI#1]
Chaves de acesso ao projecto não devem ter acesso público. O appsettings.json pode ser incluído no .gitignore para excluir esse ficheiro. Quando for incluído no docker ou kubernetes o ficheiro appsettings pode ser re-criado novamente.

**Comment by MarioFGomes** [comment]
Obrigado pela dica vou cuidar já disto

**Comment by MarioFGomes** [comment]
Issue resolvida.
os dados sensíveis de configuração foram retirados do  appsettings.json tornando assim a aplicação mais segura
